[build]
# Install Nginx and copy custom configuration
command = """
apk add --no-cache nginx
cp nginx.conf /etc/nginx/nginx.conf
"""

[start]
# Start Nginx with the custom configuration
command = "nginx -g 'daemon off;'"
